### ISSUE TITLE
Mirai Edition TODO 列表

### ISSUE THREAD

**Issue by StarWishsama** [StarWishsama/Nameless-Bot#45]
- [x] 以图搜图
- [x] 优化抽卡模拟器体验 (井机制, 舟游50连恰保底)
- [x] 优化交互体验, 加入命令帮助菜单方便使用
- [ ] 关键词禁言系统, 支持正则表达式
- [x] 命令权限系统 (Mirai side)
- [x] 强制注册机器人账号 (Mirai side)
- [x] 使用 LocalDateTime API 统一时间
- [ ] 宠物系统
- [x] 类蚂蚁庄园养花
- [x] BiliBili 直播推送
